#!/bin/bash

WLAN=wlp2s0
DRIVER=wext

# See this link for configuration and certificat
# http://www.eduroam.upmc.fr/doc/config/unix-eduroam-ttls.htm
CONF=/etc/wpa_supplicant/wpa_supplicant.conf
CERT=/root/radius.cert

# Prepare device and kill previous session
sudo killall wpa_supplicant
sudo ifconfig wlp2s0 up

# Start dhcpcd and wpa_supplicant
sudo wpa_supplicant -i $WLAN -D $DRIVER -c $CONF -d -B
sudo systemctl restart dhcpcd.service
