#!/bin/bash

WLAN=wlp2s0
ESSID=FreeWifi
MAC=76:68:B0:7C:37:25

if [ -z "$(pidof chromium)" ]; then
  chromium &> /dev/null &
fi

if ! ifconfig | grep $WLAN &> /dev/null; then
  echo "$WLAN down. Exiting"
  exit 1
fi

sudo killall dhcpcd
if [ "$1" = "ext" ]; then
  MAC=14:0C:76:EE:6B:29
fi
sudo iwconfig $WLAN essid $ESSID key open ap $MAC
sleep 1
sudo dhcpcd -4 $WLAN -C 10-wpa_supplicant -d 

if [ $? -eq 0 ]; then
  cd /etc/openvpn/Athena
  sudo screen -US vpn
  exit 0
else
  echo "No IP address :-("
  exit 1
fi
