#!/bin/bash

DWM_D=$HOME/.dwm
DWM_P=$(pidof dwm)

cd $DWM_D
makepkg -g >> PKGBUILD
makepkg -efi --noconfirm

if [ $? -eq 0 ]; then
  if [ ! -z DWM_PID ]; then
    kill -9 $DWM_P
  fi
  cd $HOME
  exit 0
else
  echo "Error :("
  cd $HOME
  exit 1
fi
