#!/bin/bash

if [ "$1" != "fac" ]; then
  export http_proxy=http://proxy.ufr-info-p6.jussieu.fr:3128
  export https_proxy=https://proxy.ufr-info-p6.jussieu.fr:3128
  export ftp_proxy=ftp://proxy.ufr-info-p6.jussieu.fr:3128
  export HTTP_PROXY=$http_proxy
  export HTTPS_PROXY=$https_proxy
fi

sudo ifconfig wlp2s0 down
sudo systemctl start dhcpcd
sudo ifconfig wlp2s0 down

# while [ -z $IP ]; do
#   IP=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -n1)
#   sleep 0.1
# done

# $SCRIPTS_DIR/vpn $1 &
#

cd /etc/openvpn/Athena
sudo screen -US vpn
