#!/bin/bash

export http_proxy=http://proxy.ufr-info-p6.jussieu.fr:3128
export https_proxy=https://proxy.ufr-info-p6.jussieu.fr:3128
export ftp_proxy=ftp://proxy.ufr-info-p6.jussieu.fr:3128
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$https_proxy
