#!/bin/bash

CONF_DIR=/etc/openvpn/$HOSTNAME

if [ "$1" = "fac" ]; then
    CONF_FILE=client_fac.conf
else
    CONF_FILE=client.conf
fi

sudo urxvt -T trash -e sudo screen -US vpn -d -m $SCRIPTS_DIR/vpn_cmd $CONF_FILE
